services:
  play_bag:
    build:
      context: .
    image: fomo-bench:latest

  evaluate_trajectory:
    build:
      context: .
    image: fomo-bench:latest

  plot_confusion_matrix:
    build:
      context: .
    image: fomo-bench:latest

  record_odometry_1:
    build:
      context: .
    image: fomo-bench:latest

  record_odometry_2:
    build:
      context: .
    image: fomo-bench:latest

  record_odometry_3:
    build:
      context: .
    image: fomo-bench:latest

  run_foxglove:
    build:
      context: .
    image: fomo-bench:latest
