FROM norlab/icpmapper:latest


RUN cd /ros2_ws/src/norlab_icp_mapper_ros && git fetch && git checkout 0e4d9b1d3caeb7cd0168bca6310ebefec0ca5015
RUN rm -rf /tmp/fomo-bench /ros2_ws/src/ros_launchers
RUN git clone https://github.com/norlab-ulaval/fomo-bench.git -b icp-mapper-noise /tmp/fomo-bench \
    && mv /tmp/fomo-bench/ros_launchers /ros2_ws/src/ros_launchers

RUN cd /ros2_ws/ \
    && source /opt/ros/humble/setup.bash \
    && export CC=clang \
    && export CXX=clang++ \
    && colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

# STOPSIGNAL SIGINT
# # add additional commands here
CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch --noninteractive ros_launchers norlabIcpMapperNoise.launch.py"]
