FROM ros:humble-ros-base

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libglew-dev libgl1-mesa-dev libegl1-mesa-dev \
    libwayland-dev libxkbcommon-dev wayland-protocols \
    libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev \
    libjpeg-dev libtiff-dev libopenexr-dev libpng-dev \
    libeigen3-dev pkg-config \
    ninja-build libepoxy-dev \
    libopencv-dev python3-pip \
    libboost-all-dev \
    && rm -rf /var/lib/apt/lists/*

# Build Pangolin from source

RUN pip3 install --no-cache-dir wheel

WORKDIR /opt
RUN git clone --recursive https://github.com/stevenlovegrove/Pangolin.git && \
    cd Pangolin && \
    git checkout eb51fea && \
    git submodule update --init --recursive && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja \
    -DCMAKE_CXX_FLAGS="-Wno-error=type-limits -Wno-type-limits" && \
    ninja && ninja install

# Clone ORB_SLAM3 source
WORKDIR /opt
RUN git clone git@github.com:norlab-ulaval/ORB-SLAM3-STEREO-FIXED.git ORB_SLAM3 && \
    cd ORB_SLAM3 && \
    git submodule update --init --recursive && \
    chmod +x build.sh && \
    ./build.sh

RUN apt-get update && apt-get install -y curl gnupg2 lsb-release
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2.list
RUN apt-get update

RUN apt-get install -y \
    ros-humble-vision-opencv \
    ros-humble-message-filters \
    ros-humble-rosbag2-storage-mcap

RUN apt-get update && apt-get install -y \
    ros-humble-rviz2 \
    ros-humble-rviz-common \
    ros-humble-rosbag2-storage-mcap \
    ros-humble-rosbag2-transport \
    ros-humble-rosbag2-storage-default-plugins

RUN mkdir -p /colcon_ws/src

RUN git clone -b humble https://github.com/norlab-ulaval/ORB_SLAM3_ROS2.git /colcon_ws/src/ORB_SLAM3_ROS2
RUN git clone https://github.com/norlab-ulaval/imu_tools.git -b fomo /colcon_ws/src/imu_tools
RUN git clone https://github.com/norlab-ulaval/norlab_imu_tools.git -b fomo /colcon_ws/src/norlab_imu_tools

RUN rosdep update
RUN rosdep install --from-paths /colcon_ws/src --ignore-src -r -y
RUN cd /colcon_ws/src/ORB_SLAM3_ROS2/vocabulary \
    && tar -xzvf ORBvoc.txt.tar.gz \
    && rm ORBvoc.txt.tar.gz

RUN . /opt/ros/humble/setup.sh && cd /colcon_ws && colcon build --symlink-install

WORKDIR /
STOPSIGNAL SIGINT

CMD ["/bin/bash", "-c", "cd /data && source /opt/ros/humble/setup.bash && source /colcon_ws/install/setup.bash && ros2 launch --noninteractive orbslam3 orb-slam3-imu.launch.py"]
