FROM ros:humble-ros-base

SHELL ["/bin/bash", "-c"]

# Fix for Hash Sum mismatch error
# from this link https://stackoverflow.com/questions/67732260/how-to-fix-hash-sum-mismatch-in-docker-on-mac
RUN echo "Acquire::http::Pipeline-Depth 0;" > /etc/apt/apt.conf.d/99custom && \
    echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99custom && \
    echo "Acquire::BrokenProxy    true;" >> /etc/apt/apt.conf.d/99custom

RUN rm -rf /var/lib/apt/lists/*
RUN apt clean\
    && apt update \
    && apt upgrade -y \
    && apt install -y \
    build-essential \
    clang cmake \
    g++ gcc gdb git \
    wget \
    libgoogle-glog-dev libgflags-dev \
    libatlas-base-dev \
    libeigen3-dev \
    libsuitesparse-dev \
    && apt clean

WORKDIR /opt
RUN wget http://ceres-solver.org/ceres-solver-2.2.0.tar.gz \
    && tar zxf ceres-solver-2.2.0.tar.gz \
    && mkdir ceres-bin \
    && cd ceres-bin \
    && cmake ../ceres-solver-2.2.0 \
    && make -j10 \
    && make test \
    && make install


# create ros workspace and other folders
RUN mkdir -p /ros2_ws/src

WORKDIR /ros2_ws/src

RUN git clone https://github.com/UTS-RI/2fast2lamaa.git
RUN git clone https://github.com/norlab-ulaval/fomo-bench.git -b 2fast2lamaa /tmp/fomo-bench \
    && mv /tmp/fomo-bench/ros_launchers /ros2_ws/src/ros_launchers


WORKDIR /ros2_ws
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN rosdep update
RUN rosdep install --from-paths /ros2_ws/src --ignore-src -r -y
RUN source /opt/ros/humble/setup.bash \
    && colcon build --symlink-install

RUN apt update && apt install -y ros-humble-rosbag2-storage-mcap \
    && apt clean

STOPSIGNAL SIGINT
# add additional commands here
CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch --noninteractive ros_launchers 2fast2lamaa.launch.py"]
