FROM ros:humble-ros-base

SHELL ["/bin/bash", "-c"]

# Fix for Hash Sum mismatch error
# from this link https://stackoverflow.com/questions/67732260/how-to-fix-hash-sum-mismatch-in-docker-on-mac
RUN echo "Acquire::http::Pipeline-Depth 0;" > /etc/apt/apt.conf.d/99custom && \
    echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99custom && \
    echo "Acquire::BrokenProxy    true;" >> /etc/apt/apt.conf.d/99custom

RUN rm -rf /var/lib/apt/lists/*
RUN apt clean\
    && apt update \
    && apt upgrade -y \
    && apt install -y \
    build-essential \
    clang cmake \
    g++ gcc gdb git \
    fuse \
    libomp-dev libboost-all-dev libeigen3-dev libyaml-cpp-dev \
    python3-pip \
    curl gnupg lsb-release \
    && apt clean

# install libraries
RUN cd / && mkdir -p libraries

WORKDIR /

# create ros workspace
RUN mkdir -p /ros2_ws/src

RUN git clone https://github.com/norlab-ulaval/imu_tools.git -b fomo /ros2_ws/src/imu_tools
RUN git clone https://github.com/norlab-ulaval/norlab_imu_tools.git -b fomo /ros2_ws/src/norlab_imu_tools
RUN git clone https://github.com/norlab-ulaval/fomo-bench.git /tmp/fomo-bench \
    && mv /tmp/fomo-bench/ros_launchers /ros2_ws/src/ros_launchers

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN rosdep update
RUN rosdep install --from-paths /ros2_ws/src --ignore-src -r -y
RUN cd /ros2_ws/ \
    && source /opt/ros/humble/setup.bash \
    && colcon build --symlink-install

STOPSIGNAL SIGINT

# add additional commands here
CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch --noninteractive ros_launchers norlabProprioceptive.launch.py"]
