FROM ros:humble-ros-base

SHELL ["/bin/bash", "-c"]

# Fix for Hash Sum mismatch error
# from this link https://stackoverflow.com/questions/67732260/how-to-fix-hash-sum-mismatch-in-docker-on-mac
RUN echo "Acquire::http::Pipeline-Depth 0;" > /etc/apt/apt.conf.d/99custom && \
    echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99custom && \
    echo "Acquire::BrokenProxy    true;" >> /etc/apt/apt.conf.d/99custom

RUN rm -rf /var/lib/apt/lists/*
RUN apt clean\
    && apt update \
    && apt upgrade -y \
    && apt install -y \
    python3-pip curl git \
    libgl1-mesa-glx \
    ros-humble-rosbag2-storage-mcap \
    ros-humble-foxglove-bridge \
    ros-humble-image-transport \
    ros-humble-cv-bridge \
    && apt clean

WORKDIR /

RUN cd /opt && git clone --recursive https://github.com/princeton-vl/DROID-SLAM.git \
    && cd DROID-SLAM \
    && pip install -r requirements.txt

RUN pip install numpy==1.26.4 scipy==1.15.3 tqdm==4.67.1 torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118

RUN apt update && apt install -y \
    nvidia-cuda-toolkit \
    gcc-10 g++-10 \
    ninja-build \
    && apt clean

RUN mkdir -p /usr/local/cuda/bin \
    && ln -s /usr/bin/nvcc /usr/local/cuda/bin/nvcc \
    && mkdir -p /usr/local/cuda/lib64 \
    && ln -s /usr/lib/x86_64-linux-gnu /usr/local/cuda/lib64 \
    && /usr/local/cuda/bin/nvcc --version

ENV CUDA_HOME=/usr/local/cuda
ENV PATH=$CUDA_HOME/bin:$PATH
ENV LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

ENV CC=/usr/bin/gcc-10
ENV CXX=/usr/bin/g++-10
ENV CUDAHOSTCXX=/usr/bin/g++-10
ENV TORCH_CUDA_ARCH_LIST="7.5"

RUN cd /opt/DROID-SLAM \
    && export CUDA_HOME=/usr/local/cuda PATH=$CUDA_HOME/bin:$PATH LD_LIBRARY_PATH=$CUDA_HOME/lib64:$CUDA_HOME/lib64 \
    && export CC=/usr/bin/gcc-10 CXX=/usr/bin/g++-10 CUDAHOSTCXX=/usr/bin/g++-10 \
    && pip install thirdparty/lietorch
RUN pip install torch-scatter -f https://data.pyg.org/whl/torch-2.0.1+cu118.html
# we need to manually specify the CUDA architecture to build the package
# TODO make this an argument
RUN cd /opt/DROID-SLAM \
    && export CUDA_HOME=/usr/local/cuda PATH=$CUDA_HOME/bin:$PATH LD_LIBRARY_PATH=$CUDA_HOME/lib64:$CUDA_HOME/lib64 \
    && export CC=/usr/bin/gcc-10 CXX=/usr/bin/g++-10 CUDAHOSTCXX=/usr/bin/g++-10 \
    && pip install -e .

# create ros workspace and other folders
RUN mkdir -p /ros2_ws/src

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN git clone https://github.com/norlab-ulaval/legs_ros_ws.git -b fomo /ros2_ws/src/legs_ros_ws
RUN git clone https://github.com/norlab-ulaval/fomo-bench.git -b ros2 /tmp/fomo-bench \
    && mv /tmp/fomo-bench/ros_launchers /ros2_ws/src/ros_launchers

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN rosdep update
RUN rosdep install --from-paths /ros2_ws/src --ignore-src -r -y
RUN cd /ros2_ws/ \
    && source /opt/ros/humble/setup.bash \
    && colcon build --symlink-install

RUN pip install viser
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
STOPSIGNAL SIGINT
# add additional commands here
CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch --noninteractive ros_launchers droid_slam.launch.py"]
